# Generated by Django 4.1.2 on 2022-11-27 23:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('number_of_lessons', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('lesson_duration', models.PositiveIntegerField(choices=[(30, '30'), (45, '45'), (60, '60')], default=30)),
                ('teacher', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fulfilled', models.BooleanField(default=False)),
                ('paid_type', models.PositiveIntegerField(choices=[(1, 'unpaid'), (4, 'overpaid'), (3, 'partially paid'), (2, 'paid')], default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
