# Generated by Django 4.1.2 on 2022-11-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson'),
        ('lessons', '0003_student'),
    ]

    operations = [
    ]
