# Generated by Django 4.1.3 on 2022-11-27 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Invoice number must only contain numbers and a dash', regex='\\w[0-9]+-[0-9]+$')])),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Username must consist of three to sixteen alphanumericals', regex='^\\w{3,}$')]),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('number_of_lessons', models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('lesson_duration', models.PositiveIntegerField(choices=[(30, '30'), (45, '45'), (60, '60')], default=30)),
                ('teacher', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fulfilled', models.BooleanField(default=False)),
                ('paid_type', models.PositiveIntegerField(choices=[(1, 'unpaid'), (2, 'paid'), (3, 'partially paid'), (4, 'overpaid')], default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
