# Generated by Django 4.1.3 on 2022-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_merge_0003_lesson_0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='paid_type',
            field=models.PositiveIntegerField(choices=[(1, 'unpaid'), (2, 'paid'), (3, 'partially paid'), (4, 'overpaid')], default=1),
        ),
    ]
