# Generated by Django 4.1.3 on 2022-11-29 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_invoice_alter_user_username_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invoice number must only contain numbers and a dash', regex='\\w[0-9]+-[0-9]+$')]),
        ),
    ]
