# Generated by Django 4.1.2 on 2022-12-06 14:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='invoice',
        ),
        migrations.AddField(
            model_name='transfer',
            name='invoice_number',
            field=models.CharField(default='0-0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='paid_type',
            field=models.PositiveIntegerField(choices=[(1, 'Unpaid'), (2, 'Paid'), (3, 'Partially paid'), (4, 'Overpaid')], default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
