# Generated by Django 4.1.2 on 2022-12-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_transfer_invoice_transfer_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='invoice_number',
            field=models.CharField(default='0-0', max_length=50),
        ),
    ]
