# Generated by Django 4.1.2 on 2022-12-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_transfer_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='invoice',
            field=models.CharField(default='No associated invoice.', max_length=25),
        ),
    ]
