# Generated by Django 4.1.2 on 2022-12-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_days_lesson_intervals_alter_lesson_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='days',
            new_name='day_of_week',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='intervals',
            new_name='week_interval',
        ),
    ]
